name: Deploy Obsidian Notes

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # - name: Install dependencies
      #   run: pip install markdown

      # - name: Install Pandoc
      #   run: sudo apt-get update && sudo apt-get install -y pandoc

      # - name: Process notes
      #   run: python process_notes.py

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.135.0/hugo_extended_0.135.0_Linux-64bit.tar.gz
          tar -xzf hugo_extended_0.135.0_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/hugo

      - name: Create Hugo site if missing
        run: |
          if [ ! -f config.toml ] && [ ! -f config.yaml ] && [ ! -f config.json ]; then
            echo "Hugo site not found. Creating a new site..."
            hugo new site site
            cd site
            echo 'title = "My blog post"' > config.toml
            git init
            git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
            echo "theme = 'ananke'" >> hugo.toml
          else
            echo "Hugo site found. Skipping creation step."
          fi

      - name: Move markdown files
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing markdown_files directory:"
          ls -la ../markdown_files || echo "markdown_files not found"
          
          cd site
          mkdir -p ./content/posts
          echo "Listing content/posts directory before copy:"
          ls -la ./content/posts
          
          echo "Copying all markdown files..."
          cp ../markdown_files/*.md ./content/posts/ || echo "No markdown files found"
          
          echo "Listing content/posts directory after copy:"
          ls -la ./content/posts
          
          echo "Content of copied file:"
          cat ./content/posts/hello.md

      - name: Add MathJax support
        run: |
          echo "=== Directory structure ==="
          tree || find . -type d
          mkdir -p site/layouts/_default/
          touch site/layouts/_default/baseof.html
          
          echo '<head>
          <meta charset="utf-8">
          <title>{{ block "title" . }}{{ .Site.Title }}{{ end }}</title>
          <script>
          MathJax = {
            tex: {
              inlineMath: [["$", "$"], ["\\(", "\\)"]],
              displayMath: [["$$", "$$"], ["\\[", "\\]"]],
              processEscapes: true
            }
          };
          </script>
          <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script></head>
          <body>{{ block "main" . }}{{ end }}{{ block "footer" . }}{{ end }}</body>' > site/layouts/_default/baseof.html

      - name: Generate site
        run: |
          echo "Current directory: $(pwd)"
          cd site
          hugo --minify --baseURL "https://sergeybondarev.github.io/site-generator-test/"
          ls -la .

      - name: Debug before deploy
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Directory structure ==="
          tree || find . -type d
          echo "=== Content of site directory ==="
          ls -la site/
          echo "=== Content of site/public ==="
          ls -la site/public || echo "Public directory not found!"
          echo "=== Hugo version ==="
          hugo version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
